/**
 * Build pipeline — materialize a client site from the template, build it.
 *
 * runJob({ slug, kind, profile, generated }):
 *   1. copy template-folio → data/builds/<slug>/ (excluding node_modules, dist, .git, .astro)
 *   2. symlink node_modules from the template (same pinned deps, no reinstall)
 *   3. write src/data/site.json (profile + generated copy) + src/content/projects/*.md
 *   4. run the Astro build (NODE_BIN env, default "node" — needs Node ≥ 22)
 *   5. return { status: 'live', distDir, usage } or throw { status: 'failed' }
 *
 * NOTE: local `dist/` = the "live" target in M1. Pushing to a per-client
 * GitHub repo + Pages (docs/architecture.md Phase A) plugs in at step 5.
 */
import { cpSync, mkdirSync, renameSync, rmSync, symlinkSync, writeFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateSite } from './generate.mjs';

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url))); // studio/
const TEMPLATE_DIR = process.env.TEMPLATE_DIR ?? path.join(ROOT, '..', 'template-folio');
const NODE_BIN = process.env.NODE_BIN ?? 'node';
const DEFAULT_PUBLIC_SITE_ROOT = (process.env.PUBLIC_BASE_URL ?? 'https://folioflash.camilleaubert.com').replace(/\/$/, '');

const slugify = (s) =>
  s.toLowerCase().normalize('NFD').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');

const yamlString = (value) => JSON.stringify(String(value ?? ''));
const projectMd = (p) => `---
title: ${yamlString(p.title)}
role: ${yamlString(p.role)}
years: ${yamlString(p.years)}
summary: ${yamlString(p.summary)}
frTitle: ${yamlString(p.frTitle ?? p.title)}
frRole: ${yamlString(p.frRole ?? p.role)}
frSummary: ${yamlString(p.frSummary ?? p.summary)}
${p.keyArt ? `keyArt: ${yamlString(p.keyArt)}\nkeyArtAlt: ${yamlString(p.keyArtAlt ?? p.title)}\n` : ''}featured: ${p.featured}
order: ${p.order}
links: ${JSON.stringify((p.links ?? []).filter((link) => link?.url && /^https?:\/\//i.test(link.url)).map((link) => ({ label: String(link.label).slice(0, 80), url: String(link.url).slice(0, 500) })))}
---

Generated by Folioflash (${p.kind ?? 'v1'}).
`;

export async function runJob({ slug, kind, profile, prompt, assets = [] }) {
  const { site: generated, projects, usage } = await generateSite({
    name: profile.name,
    craft: profile.craft,
    prompt,
    theme: profile.theme,
    motif: profile.motif,
    stylePreference: profile.stylePreference,
    kind,
    assets,
    briefProfile: profile.briefProfile ?? null,
  });

  const buildRoot = path.join(ROOT, 'data', 'builds');
  const buildDir = path.join(buildRoot, slug);
  const stagingDir = path.join(buildRoot, `.${slug}.pending-${randomUUID()}`);
  mkdirSync(buildRoot, { recursive: true });
  rmSync(stagingDir, { recursive: true, force: true });

  try {
    mkdirSync(stagingDir, { recursive: true });
    cpSync(TEMPLATE_DIR, stagingDir, {
      recursive: true,
      filter: (src) => !['node_modules', 'dist', '.git', '.astro'].includes(path.basename(src)),
    });
    const nm = path.join(stagingDir, 'node_modules');
    if (!existsSync(nm)) symlinkSync(path.join(TEMPLATE_DIR, 'node_modules'), nm, 'dir');

    writeFileSync(
      path.join(stagingDir, 'src', 'data', 'site.json'),
      `${JSON.stringify(
        {
          name: profile.name,
          nameIsPseudonym: profile.briefProfile?.nameIsPseudonym ?? false,
          craft: profile.craft,
          audience: profile.briefProfile?.audience ?? '',
          goal: profile.briefProfile?.goal ?? '',
          email: profile.email ?? 'hello@example.com',
          palette: profile.palette ?? 'paper',
          motif: generated.motif ?? profile.motif ?? 'cercles',
          projectPresentation: generated.projectPresentation ?? 'editorial',
          projectCount: projects.length,
          experiences: generated.experiences ?? [],
          articles: generated.articles ?? [],
          projects: projects.map((project) => ({
            title: project.title,
            summary: project.summary,
            ...(project.assetId ? { keyArt: `images/portfolio/${project.assetId}.webp` } : {}),
          })),
          theme: generated.theme ?? profile.theme,
          socials: [
            generated.contact?.linkedin ? { label: 'LinkedIn', url: generated.contact.linkedin } : null,
            generated.contact?.website ? { label: 'Website', url: generated.contact.website } : null,
          ].filter(Boolean),
          contactCta: generated.contact?.cta ?? '',
          tagline: generated.tagline,
          bio: generated.bio,
          designDirection: generated.designDirection,
          fr: generated.fr,
        },
        null,
        2,
      )}\n`,
    );

    const projDir = path.join(stagingDir, 'src', 'content', 'projects');
    rmSync(projDir, { recursive: true, force: true });
    mkdirSync(projDir, { recursive: true });
    const publicImageDir = path.join(stagingDir, 'public', 'images', 'portfolio');
    mkdirSync(publicImageDir, { recursive: true });
    const knownAssets = new Map();
    for (const asset of assets) {
      if (!/^[a-f0-9-]{36}$/i.test(asset.id)) continue;
      const filename = `${asset.id}.webp`;
      writeFileSync(path.join(publicImageDir, filename), asset.data, { mode: 0o644 });
      knownAssets.set(asset.id, `images/portfolio/${filename}`);
    }
    projects.forEach((project, index) => {
      const keyArt = knownAssets.get(project.assetId);
      const filename = `project-${index + 1}-${slugify(project.title).slice(0, 30)}.md`;
      writeFileSync(path.join(projDir, filename), projectMd({ ...project, kind, keyArt }));
    });

    try {
      execFileSync(NODE_BIN, ['node_modules/astro/bin/astro.mjs', 'build'], {
        cwd: stagingDir,
        timeout: 120_000,
        stdio: 'pipe',
        env: {
          ...process.env,
          FOLIOFLASH_PREVIEW: 'true',
          SITE_URL: profile.publicSiteRoot ?? DEFAULT_PUBLIC_SITE_ROOT,
          BASE_PATH: `/s/${slug}/`,
        },
      });
    } catch (err) {
      throw new Error(`astro build failed: ${String(err.stderr ?? err.message).slice(0, 500)}`);
    }

    const previousDir = existsSync(buildDir) ? `${buildDir}.previous-${randomUUID()}` : null;
    if (previousDir) renameSync(buildDir, previousDir);
    try {
      renameSync(stagingDir, buildDir);
    } catch (error) {
      if (previousDir && !existsSync(buildDir)) renameSync(previousDir, buildDir);
      throw error;
    }
    if (previousDir) {
      try { rmSync(previousDir, { recursive: true, force: true }); } catch { /* New build is live; old files can be cleaned later. */ }
    }
  } catch (error) {
    rmSync(stagingDir, { recursive: true, force: true });
    throw error;
  }

  return {
    status: 'live',
    distDir: path.join('data', 'builds', slug, 'dist'),
    absDistDir: path.join(buildDir, 'dist'),
    theme: generated.theme ?? profile.theme,
    motif: generated.motif ?? profile.motif ?? 'cercles',
    projectPresentation: generated.projectPresentation ?? profile.projectPresentation ?? 'editorial',
    designDirection: generated.designDirection,
    usage,
  };
}
