/**
 * Build pipeline — materialize a client site from the template, build it.
 *
 * runJob({ slug, kind, profile, generated }):
 *   1. copy template-folio → data/builds/<slug>/ (excluding node_modules, dist, .git, .astro)
 *   2. symlink node_modules from the template (same pinned deps, no reinstall)
 *   3. write src/data/site.json (profile + generated copy) + src/content/projects/*.md
 *   4. run the Astro build (NODE_BIN env, default "node" — needs Node ≥ 22)
 *   5. return { status: 'live', distDir, usage } or throw { status: 'failed' }
 *
 * NOTE: local `dist/` = the "live" target in M1. Pushing to a per-client
 * GitHub repo + Pages (docs/architecture.md Phase A) plugs in at step 5.
 */
import { cpSync, mkdirSync, rmSync, symlinkSync, writeFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateSite } from './generate.mjs';

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url))); // studio/
const TEMPLATE_DIR = process.env.TEMPLATE_DIR ?? path.join(ROOT, '..', 'template-folio');
const NODE_BIN = process.env.NODE_BIN ?? 'node';

const slugify = (s) =>
  s.toLowerCase().normalize('NFD').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');

const projectMd = (p) => `---
title: "${p.title.replace(/"/g, "'")}"
role: "${p.role.replace(/"/g, "'")}"
years: "${p.years.replace(/"/g, "'")}"
summary: "${p.summary.replace(/"/g, "'")}"
featured: ${p.featured}
order: ${p.order}
links: []
---

Generated by Folioflash (${p.kind ?? 'v1'}).
`;

export async function runJob({ slug, kind, profile, prompt }) {
  const { site: generated, projects, usage } = await generateSite({
    name: profile.name,
    craft: profile.craft,
    prompt,
    palette: profile.palette,
  });

  const buildDir = path.join(ROOT, 'data', 'builds', slug);
  rmSync(buildDir, { recursive: true, force: true });
  mkdirSync(buildDir, { recursive: true });
  cpSync(TEMPLATE_DIR, buildDir, {
    recursive: true,
    filter: (src) => !['node_modules', 'dist', '.git', '.astro'].includes(path.basename(src)),
  });
  const nm = path.join(buildDir, 'node_modules');
  if (!existsSync(nm)) symlinkSync(path.join(TEMPLATE_DIR, 'node_modules'), nm, 'dir');

  // site.json = profile (owner) + generated copy + palette
  writeFileSync(
    path.join(buildDir, 'src', 'data', 'site.json'),
    `${JSON.stringify(
      {
        name: profile.name,
        craft: profile.craft,
        email: profile.email ?? 'hello@example.com',
        palette: profile.palette,
        socials: [],
        tagline: generated.tagline,
        bio: generated.bio,
        fr: generated.fr,
      },
      null,
      2,
    )}\n`,
  );

  // Replace demo projects with generated ones
  const projDir = path.join(buildDir, 'src', 'content', 'projects');
  rmSync(projDir, { recursive: true, force: true });
  mkdirSync(projDir, { recursive: true });
  projects.forEach((p, i) => {
    writeFileSync(path.join(projDir, `project-${i + 1}-${slugify(p.title).slice(0, 30)}.md`), projectMd({ ...p, kind }));
  });

  try {
    execFileSync(NODE_BIN, ['node_modules/astro/bin/astro.mjs', 'build'], {
      cwd: buildDir,
      timeout: 120_000,
      stdio: 'pipe',
    });
  } catch (err) {
    throw new Error(`astro build failed: ${String(err.stderr ?? err.message).slice(0, 500)}`);
  }

  return { status: 'live', distDir: path.join('data', 'builds', slug, 'dist'), absDistDir: path.join(buildDir, 'dist'), usage };
}
